name: CI

on:
  pull_request:
    types: [opened, reopened]

jobs:
    tests:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set up Python 3.11
              uses: actions/setup-python@v5
              with:
                python-version: '3.11'

            -  name: Install requirements
               run: pip install -r requirements.txt

            # - name: Define a cache for the virtual environment based on the dependencies lock file
            #   uses: actions/cache@v4
            #   with:
            #     path: ./.venv
            #     key: venv-${{ hashFiles('poetry.lock') }}

            # - name: Install the project dependencies
            #   run: poetry install


            - name: Run Training
              run: |
                python src/train.py
                echo "[!] Training Completed "

            # - name: Run the automated tests
            #   env:
            #     PYTHONPATH: .
            #   run: poetry run pytest -v
