name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
    training:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set up Python 3.11
              uses: actions/setup-python@v5
              with:
                python-version: '3.11'

            -  name: Install requirements
               run: pip install -r requirements.txt


            - name: Run Training
              run: |
                python src/train.py
                echo "[!] Training Completed "

